export const sidebarConstant = [
  // Core Components
  { id: 1, name: "CPU", required: true, coreComponents: true, selected: false },
  {
    id: 2,
    name: "CPU Cooler",
    required: false,
    coreComponents: true,
    selected: false,
  },
  {
    id: 3,
    name: "Motherboard",
    required: true,
    coreComponents: true,
    selected: false,
  },
  { id: 4, name: "RAM", required: true, coreComponents: true, selected: false },
  {
    id: 5,
    name: "Storage",
    required: true,
    coreComponents: true,
    selected: false,
  },
  {
    id: 6,
    name: "Graphics Card",
    required: false,
    coreComponents: true,
    selected: false,
  },
  {
    id: 7,
    name: "Power Supply",
    required: false,
    coreComponents: true,
    selected: false,
  },
  {
    id: 8,
    name: "Casing",
    required: false,
    coreComponents: true,
    selected: false,
  },
  //   PeriPherals & others
  {
    id: 9,
    name: "Monitor",
    required: false,
    coreComponents: false,
    selected: false,
  },
  {
    id: 10,
    name: "Casing Cooler",
    required: false,
    coreComponents: false,
    selected: false,
  },
  {
    id: 11,
    name: "Keyboard",
    required: false,
    coreComponents: false,
    selected: false,
  },
  {
    id: 12,
    name: "Mouse",
    required: false,
    coreComponents: false,
    selected: false,
  },
  {
    id: 13,
    name: "Anti Virus",
    required: false,
    coreComponents: false,
    selected: false,
  },
  {
    id: 14,
    name: "Headphone",
    required: false,
    coreComponents: false,
    selected: false,
  },
  {
    id: 15,
    name: "UPS",
    required: false,
    coreComponents: false,
    selected: false,
  },
];
