import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProviders } from "./themeProviders";
import PageLayout from "./pageLayout";
import ReduxProvider from "./ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviders>
          <ReduxProvider>
            <PageLayout>{children}</PageLayout>
          </ReduxProvider>
        </ThemeProviders>
      </body>
    </html>
  );
}
